name: Deploy to Remote Server

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    name: Deploys To Server

    steps:
      - name: Publish Files
        uses: kentaasvang/scp_deploy@v0.8.2b
        with:
          host: "80.212.216.61"
          user: admin
          private_key: ${{ secrets.PI_ID_RSA_PRIV_KEY }}
          port: 2222
          source_folder: ./
          destination_folder: /home/admin/asvang-it.no
