name: Deploy to Remote Server

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    name: Deploys To Server

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: SCP Deploy
      uses: kentaasvang/scp_deploy@v2.0.4b
      with:
        host: 80.212.216.61
        port: 2222
        user: admin
        private_key: ${{ secrets.PI_ID_RSA_PRIV_KEY }}
        source_folder: ./
        destination_folder: /home/admin/testfolder
